# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'buat_db.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import mysql.connector

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(408, 317)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(10, 20, 101, 16))
        self.label.setObjectName("label")
        self.txtNamaDB = QtWidgets.QLineEdit(Dialog)
        self.txtNamaDB.setGeometry(QtCore.QRect(110, 20, 281, 20))
        self.txtNamaDB.setObjectName("txtNamaDB")
        self.btnBuatDB = QtWidgets.QPushButton(Dialog)
        self.btnBuatDB.setGeometry(QtCore.QRect(10, 250, 181, 23))
        self.btnBuatDB.setObjectName("btnBuatDB")
        self.btnBuatDB.clicked.connect(self.create_db)

        self.btnTestingKoneksiDB = QtWidgets.QPushButton(Dialog)
        self.btnTestingKoneksiDB.setGeometry(QtCore.QRect(210, 250, 181, 23))
        self.btnTestingKoneksiDB.setObjectName("btnTestingKoneksiDB")
        self.btnTestingKoneksiDB.clicked.connect(self.connect_db)

        self.lblOutput = QtWidgets.QLabel(Dialog)
        self.lblOutput.setGeometry(QtCore.QRect(10, 280, 181, 16))
        self.lblOutput.setObjectName("lblOutput")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Buat Database"))
        self.label.setText(_translate("Dialog", "BUAT BASIS DATA"))
        self.btnBuatDB.setText(_translate("Dialog", "BUAT DATABASE"))
        self.btnTestingKoneksiDB.setText(_translate("Dialog", "TESTING KONEKSI"))
        self.lblOutput.setText(_translate("Dialog", "TextLabel"))

    def create_db(self):
        try:
            myDB = mysql.connector.connect(
                host="localhost",
                user="root",
                password="root"
            )

            dbName = self.txtNamaDB.text()
            
            myCursor = myDB.cursor()
            myCursor.execute("CREATE DATABASE {}".format(dbName))
            self.lblOutput.setText("Berhasil membuat database {}".format(dbName))
        except mysql.Error as ex:
            self.lblOutput.setText("Gagal membuat database")

    def connect_db(self):
        try:
            dbName = self.txtNamaDB.text()
            myDB = mysql.connector.connect(
                host="localhost",
                user="root",
                password="root",
                database=dbName
            )

            self.lblOutput.setText("Berhasil koneksi database {}".format(dbName))
        except mysql.Error as ex:
            self.lblOutput.setText("Gagal koneksi database {}".format(dbName))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
